application: jovial-meridian-94519  
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "30d"

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*)
  script: conversation.app
