application: talk-tonic
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "30d"

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /googlelogo.jpg
  static_files: googlelogo.jpg
  upload: googlelogo.jpg
- url: /alchemylogo.png
  static_files: alchemylogo.png
  upload: alchemylogo.png
- url: /styles.css
  static_files: styles.css
  upload: styles.css
- url: /materialize.js
  static_files: materialize.js
  upload: materialize.js
- url: /materialize.css
  static_files: materialize.css
  upload: materialize.css
- url: /chat.js
  static_files: chat.js
  upload: chat.js
- url: /people.png
  static_files: people.png
  upload: people.png
- url: /(.*)
  script: conversation.app
